### ISSUE TITLE
Drop support for 3.8.x kernel and add support for 4.1.x kernel

### ISSUE THREAD

**Issue by fivdi** [fivdi/bot-io#2]
I'm going to make the assumption that `bot-io` isn't actually used by anyone and update everything to support the 4.1.x kernel. These changes will result support for the 3.8.x kernel being dropped.

**Comment by popasquat89** [comment]
Any idea when this will come to fruition? Using bot-io with node.js 0.12 on 4.1.18, iot 4GB build, with no luck.

`
/home/debian/*/*/node_modules/bot-io/lib/slots.js:18
    throw new Error('No unique slots file matching \'' + PATTERN + '\' found')
          ^
Error: No unique slots file matching '/sys/devices/bone_capemgr.*/slots' found
    at /home/debian/*/*/node_modules/bot-io/lib/slots.js:18:11
    at Object.<anonymous> (/home/debian/*/*/node_modules/bot-io/lib/slots.js:22:2)
`

**Comment by fivdi** [comment]
It's about 75% finished but I'm working on other projects at the moment. I'm afraid there's no fixed date for the completion of the remaining 25%.

**Comment by fivdi** [comment]
bot-io v1.0.0 dropped support for the 3.8.x kernel and added support for the 4.1.x-ti kernel.
